from datetime import timedelta

# Constellation-specific parameters
CONST_PARAMS = {
    "GPS": {"time_system": "GPST", "prefix": "G", "time_offset": timedelta(0)},
    "BeiDou": {
        "time_system": "BDT",
        "prefix": "C",
        "time_offset": timedelta(hours=8),
    },
    # TODO Add other constellations
}

EPHEMERIS_FIELDS: dict[str, list[str]] = {
    "GPS": [
        "accuracy",
        "cic",
        "cis",
        "clock_bias",
        "clock_drift",
        "clock_drift_rate",
        "crc",
        "crs",
        "cuc",
        "cus",
        "deltaN",
        "e",
        "fitInt",
        "health",
        "i0",
        "idot",
        "iodc",
        "iode",
        "l2Codes",
        "l2p",
        "m0",
        "omega",
        "omega0",
        "omegaDot",
        "sqrta",
        "t_tm",
        "tgd",
        "toe",
    ],
    "BeiDou": [
        "clock_bias",
        "clock_drift",
        "clock_drift_rate",
        "aode",
        "crs",
        "deltaN",
        "m0",
        "cuc",
        "e",
        "cus",
        "sqrta",
        "toe",
        "cic",
        "omega0",
        "cis",
        "i0",
        "crc",
        "omega",
        "omegaDot",
        "idot",
        "accuracy",
        "tgd1b1b3",
        "tgd2b2b3",
        "aodc",
    ],
    "GLONASS": [],
    "Galileo": [],
    "QZSS": [],
    "SBAS": [],
}
