services:
  calibrator:
    build: .
    image: pytecgg-batch
    container_name: pytecgg-batch
    environment:
      - SAVE_PARQUET=${SAVE_PARQUET:-True}
      - SAVE_CSV=${SAVE_CSV:-False}
      - SAVE_STATIC_PLOTS=${SAVE_STATIC_PLOTS:-False}
      - SAVE_INTERACTIVE_PLOTS=${SAVE_INTERACTIVE_PLOTS:-False}
      - PLOT_DPI=${PLOT_DPI:-300}
      - PROCESS_MODE=${PROCESS_MODE:-DAILY}
      - VERBOSE=${VERBOSE:-1}
    volumes:
      - ${INPUT_DIR:-./input}:/data/input
      - ${OUTPUT_DIR:-./output}:/data/output
      - ${NAV_DIR:-./nav}:/data/nav